
spring:
  jackson.default-property-inclusion: NON_EMPTY
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    spring.jpa.properties.hibernate:
      jdbc.batch_size: 20
      order_inserts: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true


  #Azure Cloud
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            credential.client-id: client_ID
            credential.client-secret: CLIENT_SECRET
            endpoint: https://???????.vault.azure.net/
            profile.tenant-id: TENANT_ID
